"comment" = { fg = "comment" }
"comment.block.documentation" = { bg = "comment_doc", modifiers = ["normal"] }

"constant" = { fg = "t11" }
"function" = { fg = "t10" }
"function.method" = { fg = "t10" }
"function.macro" = { fg = "t8" }
"keyword.storage.modifier" = { fg = "t8" }
"keyword.control.import" = { fg = "t8" }
"keyword.control" = { fg = "t8" }
"keyword.function" = { fg = "t7" }
"keyword" = { fg = "t8" }
"operator" = { fg = "t9" }
"punctuation" = { fg = "t9" }
"string" = { fg = "t6", modifiers = ["normal"] }
"string.regexp" = { fg = "t6" }
"tag" = { fg = "t4" }
"type" = { fg = "t4", modifiers = ["normal"] }
"namespace" = { fg = "t4", modifiers = ["normal"] }
"variable" = { fg = "t4" }
"label" = { fg = "t4" }

"diff.plus" = { fg = "diff_plus" }
"diff.delta" = { fg = "diff_delta" }
"diff.delta.moved" = { fg = "diff_delta_moved" }
"diff.minus" = { fg = "diff_minus" }

"ui.cursor.insert" = { fg = "t2", bg = "highlight" }
"ui.cursor.select" = { fg = "t2", bg = "highlight_two" }
"ui.cursor" = { fg = "t1", bg = "highlight_three" }
"ui.cursor.match" = { fg = "highlight", bg = "selection", modifiers = ["normal"] }

"ui.linenr" = { fg = "t3" }
"ui.linenr.selected" = { fg = "highlight_three" }
"ui.gutter" = { }

"ui.background" = { bg = "t1"}
"ui.background.separator" = { bg = "t1" }
"ui.help" = { fg = "t4" }
"ui.menu" = { fg = "t4" }
"ui.menu.selected" = { fg = "highlight_three" }
"ui.popup" = { fg = "t4" }
"ui.window" = { fg = "t4" }

"ui.selection.primary" = { bg = "selection" }
"ui.selection" = { bg = "selection" }

"ui.cursorline.primary" = { bg = "t1" }

"ui.statusline" = { fg = "t4" }
"ui.statusline.inactive" = { fg = "t4" }
"ui.statusline.normal" = { fg = "t3" }
"ui.statusline.insert" = { fg = "t3" }
"ui.statusline.select" = { fg = "highlight", bg = "t4" }

"ui.text" = { fg = "t4" }
"ui.text.focus" = { fg = "highlight_three", modifiers = ["normal"] }
"ui.virtual.ruler" = { bg = "t1" }
"ui.virtual.indent-guide" = { fg = "t3" }
"ui.virtual.whitespace" = { fg = "t3" }

"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.hint" = { underline = { color = "display", style = "curl" } }

"error" = { fg = "error", modifiers = ["bold"] }
"warning" = { fg = "warning", modifiers = ["bold"] }
"info" = { fg = "info", modifiers = ["bold"] }
"hint" = { fg = "display", modifiers = ["bold"] }
"special" = { fg = "t7", modifiers = ["bold"] }

"markup.heading" = { fg = "t4" }
"markup.list" = { fg = "t4" }
"markup.bold" = { fg = "t4" }
"markup.italic" = { fg = "t4" }
"markup.strikethrough" = { fg = "error", modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "t4", modifiers = ["underlined"] }
"markup.link.text" = { fg = "t4" }
"markup.quote" = { fg = "t4" }
"markup.raw" = { fg = "t4" }

# "constant" = { fg = "t11" }
# "function" = { fg = "t10" }
# "function.method" = { fg = "t10" }
# "function.macro" = { fg = "t7" }
# "keyword.storage.modifier" = { fg = "t7" }
# "keyword.control.import" = { fg = "t8" }
# "keyword.control" = { fg = "t8" }
# "keyword.function" = { fg = "t7" }
# "keyword" = { fg = "t6" }
# "operator" = { fg = "t8" }
# "punctuation" = { fg = "t9" }
# "string" = { fg = "t6", modifiers = ["normal"] }
# "string.regexp" = { fg = "t6" }
# "tag" = { fg = "t4" }
# "type" = { fg = "t8", modifiers = ["normal"] }
# "namespace" = { fg = "t6", modifiers = ["normal"] }
# "variable" = { fg = "t4" }
# "label" = { fg = "t4" }

[palette]
t1               = "#050505"
t2               = "#252525"
t3               = "#656565"
t4               = "#757575"
t5               = "#353535"
t6               = "#454545"
t7               = "#a5a5a5"
t8               = "#959595"
t9               = "#ffffff"
t10              = "#656565"
t11              = "#c5c5c5"

highlight        = "#c5c5c5"
highlight_two    = "#252525"
highlight_three  = "#c5c5c5"
selection        = "#868686"
black            = "#000000"
comment          = "#303530"
comment_doc      = "#303530"
error            = "#dd0000"
warning          = "#ddae00"
display          = "#00aadd"
info             = "#bababa"
diff_minus       = "#dd0000"
diff_delta       = "#0000dd"
diff_plus        = "#00dd00"
diff_delta_moved = "#aabbcc"

