theme = "rose_pine_moon"
# theme = "kaolin-dark"
# theme = "fleet_dark"

[editor]


idle-timeout       = 5
scrolloff          = 7
scroll-lines       = 5
true-color         = true
mouse              = true
cursorline         = true
cursorcolumn       = true
auto-completion    = false
completion-replace = true
auto-save          = true
auto-info          = true
rulers             = [79]
undercurl          = true
line-number        = "absolute"
bufferline         = "multiple"
gutters            = ["diagnostics","line-numbers","spacer"]
# jump-label-alphabet = "eirsaotndhfuywgm(cplbjvkx)z_"

[editor.indent-guides]

render      = true
character   = "|"
skip-levels = 0

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'
'|' = '|'

[editor.lsp]

enable                      = true
display-messages            = true
auto-signature-help	        = true
display-inlay-hints	        = false
display-signature-help-docs	=	true
snippets                    = true


[editor.smart-tab]
enable = false

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]

hidden = true


[editor.search]
smart-case = false

[editor.soft-wrap]

enable = false

[editor.statusline]

left = [ "mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["workspace-diagnostics", "diagnostics", "position", "file-encoding", "file-line-ending", ]
separator = "|"
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Select"

[keys.normal]

esc   = ["collapse_selection", "keep_primary_selection"]
ret   = ["open_below", "normal_mode"]
tab   = [":bn"]
S-tab = [":bp"]
l     = ["move_char_right"]
h     = ["move_char_left"]
k     = ["move_line_up","align_view_center"]
j     = ["move_line_down","align_view_center"]
"{"   = ["goto_prev_paragraph", "collapse_selection"]
"}"   = ["goto_next_paragraph", "collapse_selection"]
C-h   = ["select_prev_sibling"]
C-j   = ["shrink_selection"]
C-k   = ["expand_selection"]
C-l   = ["select_next_sibling"]
"*"   = ["move_prev_word_start", "move_next_word_end", "search_selection"]

[keys.normal.space.e]
  w = ":write!"
"." = "file_picker_in_current_buffer_directory"

[keys.normal.space.c]

r = [":w", ":config-reload"]
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[keys.insert]

C-backspace = ["delete_word_backward"]
C-b         = ["insert_at_line_start"]
C-e         = ["insert_at_line_end"]
C-l         = ["move_char_right","align_view_center"]
C-h         = ["move_char_left","align_view_center"]
C-k         = ["move_line_up","align_view_center"]
C-j         = ["move_line_down","align_view_center"]


[keys.select."]"]
"]" = "goto_next_paragraph"

[keys.select."["]
"[" = "goto_prev_paragraph"

