# theme = "github_dark_transparent"
theme = "dark_plus"
# theme = "solarized_dark"
# theme = "tokyonight_storm"
# theme = "hex_steel_transparent"
# theme = "fleet_dark"

[editor]

idle-timeout    = 1
scrolloff       = 8
true-color      = true
mouse           = true
cursorline      = true
cursorcolumn    = true
auto-completion = false
auto-save       = true
rulers          = [80]
line-number     = "absolute"
bufferline      = "multiple"
# jump-label-alphabet = "eirsaotndhfuywgm(cplbjvkx)z_"

[editor.smart-tab]
enable = false

[editor.cursor-shape]

insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]

hidden = false


[editor.search]
smart-case = false

[editor.soft-wrap]

enable = false

[editor.statusline]

left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "|"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.indent-guides]

render      = true
character   = "|"
skip-levels = 0


[editor.lsp]

enable                      = true
display-messages            = true
auto-signature-help	        = true
display-inlay-hints	        = false
display-signature-help-docs	=	true
snippets                    = true

[keys.normal]

esc   = ["collapse_selection", "keep_primary_selection"]
ret   = ["open_below", "normal_mode"]
tab   = ":bn"
S-tab = ":bp"
l     = ["move_char_right"]
h     = ["move_char_left"]
k     = ["move_line_up","align_view_center"]
j     = ["move_line_down","align_view_center"]
"{"   = ["goto_prev_paragraph", "collapse_selection"]
"}"   = ["goto_next_paragraph", "collapse_selection"]
C-h   = "select_prev_sibling"
C-j   = "shrink_selection"
C-k   = "expand_selection"
C-l   = "select_next_sibling"
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"] # vim


up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"

[keys.normal.space.e]
  w = ":write!"
"." = "file_picker_in_current_buffer_directory"


[keys.normal.space.c]

r = [":w", ":config-reload"]
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"

[keys.insert]

C-backspace = ["delete_word_backward"]
C-b         = ["insert_at_line_start"]
C-e         = ["insert_at_line_end"]
C-p         = ["move_prev_word_start"]
C-n         = ["move_next_word_end"]
C-l         = ["move_char_right"]
C-h         = ["move_char_left"]
C-k         = ["move_line_up","align_view_center"]
C-j         = ["move_line_down","align_view_center"]
C-d         = ["half_page_down", "goto_window_center"]
C-u         = ["half_page_up", "goto_window_center"]

# to learn good habits
up       = "no_op"
down     = "no_op"
left     = "no_op"
right    = "no_op"
pageup   = "no_op"
pagedown = "no_op"
home     = "no_op"
end      = "no_op"

[keys.select."]"]
"]" = "goto_next_paragraph"

[keys.select."["]
"[" = "goto_prev_paragraph"

