theme = "rose_pine"

[editor]
auto-completion           = true
auto-info                 = true
auto-save                 = true
bufferline                = "multiple"
completion-trigger-len    = 2
completion-replace        = true
preview-completion-insert = true
cursorcolumn              = true
cursorline                = true
gutters                   = ["diff","line-numbers","spacer"]
idle-timeout              = 5
jump-label-alphabet       = "eirsaotndhfuywgm(cplbjvkx)z_"
line-number               = "relative"
mouse                     = true
rulers                    = [80]
scroll-lines              = 5
scrolloff                 = 10
true-color                = true
undercurl                 = true

[editor.statusline]
left = ["mode","spacer","file-name","spacer","file-modification-indicator","spacer","version-control"]
center = ["spinner","workspace-diagnostics","spacer"]
right = ["primary-selection-length","spacer","register","spacer","position","separator","total-line-numbers","separator","position-percentage","file-type","file-encoding","file-line-ending"]
separator = ":"
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.lsp]
auto-signature-help	        = true
display-inlay-hints	        = false
display-messages            = true
display-signature-help-docs	=	true
enable                      = true
snippets                    = true

[editor.indent-guides]
character   = "|"
render      = true
skip-levels = 0

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'

[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
follow-symlinks = true
deduplicate-links = true
parents = false
max-depth = 3

[editor.search]
smart-case = false

[editor.soft-wrap]
enable = false


[keys.normal]
C-h   = ["select_prev_sibling"]
C-j   = ["shrink_selection"]
C-k   = ["expand_selection"]
S-D   = ["delete_selection_noyank"]
C-l   = ["select_next_sibling"]
esc   = ["collapse_selection", "keep_primary_selection"]
"}"   = ["goto_next_paragraph", "collapse_selection"]
"{"   = ["goto_prev_paragraph", "collapse_selection"]
h     = ["move_char_left"]
j     = ["move_line_down","align_view_center"]
k     = ["move_line_up","align_view_center"]
l     = ["move_char_right"]
"*"   = ["move_prev_word_start", "move_next_word_end", "search_selection"]
ret   = ["open_below", "normal_mode"]
S-tab = [":bp"]
tab   = [":bn"]
X     = ["select_line_above"]

[keys.normal.space.q]
  q = [":reload-all",":write-quit-all!"]

[keys.normal.space.l]
s = ":lsp-stop"
r = ":lsp-restart"

[keys.normal."+"]
m = ":run-shell-command cd .. && make"

[keys.normal.space.c]
l = ":o ~/.config/helix/languages.toml"
o = ":config-open"
r = [":w", ":config-reload"]

[keys.insert]
C-backspace = ["delete_word_backward"]
C-b         = ["insert_at_line_start"]
C-e         = ["insert_at_line_end"]
C-h         = ["move_char_left","align_view_center"]
C-j         = ["move_line_down","align_view_center"]
C-k         = ["move_line_up","align_view_center"]
C-l         = ["move_char_right","align_view_center"]

[keys.select."]"]
"]" = "goto_prev_paragraph"

[keys.select."["]
"[" ="goto_next_paragraph" 

