[[language]]
name = "c"
scope = "source.c"
file-types = ["c","h"]
roots = ["Makefile","run.sh","build.zig"]
diagnostic-severity = "Error"
block-comment-tokens = {start = "/*", end = "*/"}
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "pipx run c_formatter_42", args = [""]}

[language-server.clangd]
command = "clangd"
