[[language]]
name = "c"
scope = "source.c"
file-types = ["c","h"]
roots = ["Makefile","run.sh","build.zig"]
diagnostic-severity = "Error"
block-comment-tokens = {start = "/*", end = "*/"}
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "pipx run c_formatter_42", args = [""]}
language-servers = ["gpt", "clangd"]

[language-server.gpt]
command = "bun"
args = ["--inspect=0.0.0.0:6499", "run", "helix-gpt", "--handler", "copilot"]
timeout = 30

[language-server.clangd]
command = "clangd"

[[language]]
name = "zig"
scope = "source.zig"
file-types = ["zig"]
roots = ["build.zig","build.zig.zon"]
diagnostic-severity = "Error"
auto-format = false
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-servers = ["zigpt", "zls"]

[language-server.zigpt]
command = "bun"
args = ["--inspect=0.0.0.0:6499", "run", "helix-gpt", "--handler", "copilot"]
timeout = 30

[language-server.zls]
command = "zls"
