[[language]]
name = "c"
scope = "source.c"
file-types = ["c","h"]
roots = ["Makefile","run.sh","build.zig"]
diagnostic-severity = "Error"
# block-comment-tokens = {start = "/*", end = "*/"}
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "pipx run c_formatter_42", args = [""]}
language-servers = ["clangd"]


[language-server.clangd]
command = "clangd"

[[language]]
name = "zig"
scope = "source.zig"
file-types = ["zig"]
roots = ["build.zig","build.zig.zon", "zls.build.json"]
diagnostic-severity = "Error"
auto-format = false
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-servers = ["zls"]

[language-server.zls]
command = "zls"
